export const ActionTypes = {
  SET_CHARECTER: "SET_CHARECTER",
    SELECTED_CHARECTER: "SELECTED_CHARECTER",
  MOVIE_DETAILS: "MOVIE_DETAILS",
  PAGE_NUMBER:"PAGE_NUMBER",
  REMOVE_SELECTED_CHARECTER: "REMOVE_SELECTED_CHARECTER",
};
